import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Header from '@/components/navbar'
import Footer from '@/components/footer'

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['100', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
    title: 'Full Stack Developer | Riad',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang='en'>
            <body className={poppins.className}>
                <Header />
                <main>{children}</main>
                <Footer />
            </body>
        </html>
    )
}
