import Footer from '@/components/footer'
import Header from '@/components/navbar'
import { ThemeProvider } from '@/components/theme-provider'
import AuthProvider from '@/lib/AuthProvider'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['100', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
    title: 'Full Stack Developer | Riad',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={cn('', poppins.className)}>
                <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
                    <AuthProvider>
                        <Header />
                        <main className='min-h-screen'>{children}</main>
                        <Footer />
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}
